---
version: "3.7"

services:
  app:
    image: zhd4nov/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5