---
version: "3.7"

services:
  app:
    image: zhd4nov/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    env_file:
      - .env
    command: sh -c "
     sleep 5 &&
     make test"
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5