---
version: "3.7"

services:
  app:
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_USERNAME}
    image: zhd4nov/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    command: sh -c "
     sleep 5 &&
     make test"
    depends_on:
      - db

  db:
    environment:
      - POSTGRES_PASSWORD=${DATABASE_USERNAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_USERNAME}
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5